### ISSUE TITLE
Interop events are ignored in wait lists for CUDA adapter

### ISSUE THREAD

**Issue by alexbatashev** [oneapi-src/unified-runtime#1491]
Whenever I try to submit more than one interop event as a waitlist to urEnqueueKernelLaunch, only the first event is being considered. Apparently, this is due to the way events are filtered here:

https://github.com/oneapi-src/unified-runtime/blob/03b71483168c091d08d86dec8b1f1c76bff19af5/source/adapters/cuda/event.hpp#L187-L200

For interop events the stream is always 0, however, it is not guaranteed that the external events have been submitted to the same stream.

**Comment by JackAKirk** [comment]
@alexbatashev CUDA does not provide an event API to retrieve the stream associated with an CUevent from the CUevent. The only solution to this that I can see is therefore to switch to waiting on every event instead of using the std::sort algorithm to select the latest event for each stream.
I have benchmarked this and it turns out that for a small number of completed events, ~10, the different in performance between waiting on every event and using the sort is negligible. However up to at least a list of 10000 events (The max number I've benchmarked) the performance difference increases such that waiting on all 10000 events submitted to the same stream is almost twice as slow compared to using the sort to find the latest event in the stream and only waiting on that one. This performance differnce is of order a microsecond at the 10000 events case.

I think that this drop in performance might be acceptable since I imagine that syncing a list of 10000 events might be quite rare, and a list of 10 more common. However it would be good to get your input, and gain more insight into the importance of this issue for interop events:
- Do you think that this interop event issue will be a common issue?
- An alternative approach could be to better document this issue, pointing out to users that they can manually wait on each event separately instead of providing a list of events to solve this issue: do you think that this might be better than fixing the issue in the way I describe above, that comes with the associated performance issue?
Thanks

**Comment by alexbatashev** [comment]
> Do you think that this interop event issue will be a common issue?

Yes, the way I encountered this issue is by trying to integrate UR into an existing application that uses cuBLAS. Using vendor-provided libraries seems to be rather logical and wide-spread.

I also don't think that 2x performance drop is acceptable. In my case, I had a lot of kernels, that on A100 GPU would simply execute too quickly. 2x increased overhead on synchronization would mean 30-40% drop for my workloads.

Something, that might work much better is adding a new API to record stream onto event for backends that use Stream as an abstraction. ATen has a similar API, and I think it is reasonable to assume that if users call interop APIs, they'd know which stream was used to create that event.

**Comment by JackAKirk** [comment]
> > Do you think that this interop event issue will be a common issue?
> 
> Yes, the way I encountered this issue is by trying to integrate UR into an existing application that uses cuBLAS. Using vendor-provided libraries seems to be rather logical and wide-spread.
> 
> I also don't think that 2x performance drop is acceptable. In my case, I had a lot of kernels, that on A100 GPU would simply execute too quickly. 2x increased overhead on synchronization would mean 30-40% drop for my workloads.
> 
> Something, that might work much better is adding a new API to record stream onto event for backends that use Stream as an abstraction. ATen has a similar API, and I think it is reasonable to assume that if users call interop APIs, they'd know which stream was used to create that event.

OK sure, I can make create a new interop api for make_event that takes a native stream.

Thanks for the input.

**Comment by hdelan** [comment]
Thanks for opening ticket. First and foremost we need to fix the bug in the CUDA adapter that is causing some interop events to be ignored.

Extending the `make_event` interface to also take a `cuStream_t` is a very backend-specific extension. A better approach may be to use host tasks. We are currently in the process of remodelling host tasks to enable greater asynchrony than the current design. When the specification is updated you should get all the information (about streams etc) that you want handed to the plugin libraries. As such, I would wait a little bit until the new specification is made public and has been implemented in DPC++. This will most likely take in the region of 3 months. In the meantime feel free to have a look a draft PR for some of the extension: https://github.com/intel/llvm/pull/12921 . The final extension will likely look slightly different to this.

**Comment by hdelan** [comment]
I have added a fix [here](https://github.com/oneapi-src/unified-runtime/pull/1753). A better alternative is to use this [new experimental extension](https://github.com/intel/llvm/pull/14136) which has been taken from AdaptiveCpp. This will perform all the necessary scheduling without much overhead, provided the dependencies are correctly passed to the submit call.

**Comment by npmiller** [comment]
@hdelan both of the patches are merged is this resolved now?

**Comment by hdelan** [comment]
Yep I think this ticket can be closed

**Comment by npmiller** [comment]
Perfect, thanks!

Closing this now as we believe this is resolved, @alexbatashev feel free to re-open if the issue persists.
