### ISSUE TITLE
Design interface to expose device memory heaps to users

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#176]
Some devices can contain multiple types of device memory with different sizes and characteristics. It is often necessary to utilize these different types of memory to access the best performance on that device. Vulkan is an example of an API which has the concept of memory heaps to expose different memory types.

Unified Runtime should provide a mechanism to expose these memory types. This issue should be used to track the design of such an interface.

**Comment by jandres742** [comment]
@kbenzie : could you share reference to the Vulkan API you mentioned?

**Comment by kbenzie** [comment]
It's spread across the Vulkan specification, search for _heap_ in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html

**Comment by igchor** [comment]
I think that our long-term goal should be to allow applications to use UMA directly for memory management and support interop between UMA and UR (by allowing to use UR as a memory provider or by adding some extra APIs that would return UMA types). Of course, this will require productizing UMA.

For the short term perhaps we could extend ur_usm_mem_flags_t with a pool id and allow users to configure/create memory pools either through a new API or using an environmental variable.

@vinser52 @pbalcer any other ideas?

**Comment by igchor** [comment]
> It's spread across the Vulkan specification, search for _heap_ in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html

There is also a library build on top of Vulkan that simplifies memory management: https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/custom_memory_pools.html

**Comment by vinser52** [comment]
> For that, I think that our long-term goal should be to allow applications to use UMA directly for memory management and support interop between UMA and UR (by allowing to use UR as a memory provider or by adding some extra APIs that would return UMA types). Of course, this will require productizing UMA.

I think we have no final answer yet. Perhaps, we can think about a more high-level abstraction compared to what UMA is provided. UMA allows explicitly choosing a heap manager and memory provider to create a pool. The possible higher-level abstraction can try to do that automatically based on user requirements/properties (some kind of indirection). My point is that we need to brainstorm what kind of API the UR should/can provide on top of UMA. But direct usage of UMA should be also possible if someone wants full control.
 
> For the short term perhaps we could extend ur_usm_mem_flags_t with a pool id and allow users to configure/create memory pools either through a new API or using an environmental variable.

I believe it should be enough to address the OpenMP needs. For me, OpenMP uses case looks like a requirement to support the sub-allocator (when a pool for dedicated objects is created on top of existing allocation API).

**Comment by kbenzie** [comment]
@igchor design a declarative API for exposing types of memory pools.

**Comment by igchor** [comment]
Since most likely we would extend ur_usm_mem_flags_t it's also related to: https://github.com/oneapi-src/unified-runtime/issues/116

**Comment by igchor** [comment]
I think we have the following specific requirements for the allocation API (based on OpenMP use case):
1. Perform memory pooling and allow using `memAdvise` flags on pooled memory.
2. Allow allocating zeroed memory
3. Allow isolating allocations (e.g. runtime vs user allocations)

First, we should extend `ur_mem_advice_t` and `ur_usm_mem_flags_t` as described in the appropriate issues. Since OpenMP uses `memAdvise` just after allocation only, we can solve 1. by just passing appropriate parameters to `ur_usm_mem_flags_t`.

We might also consider making `ur_usm_mem_flags_t` and `ur_mem_advice_t` equivalent (add MOSTLY_ATOMIC, MOSTLY_NON_ATOMIC to `ur_usm_mem_flags_t`). For example, in L0 properties like "BIAS_CACHED", "BIAS_UNCACHED", "INITIAL_PLACEMENT" are supported by both `ze_host_mem_alloc_flag_t` and `ze_memory_advice_t`. Not all properties are like that, though - I'm not sure why.

To support 2. we can add `UR_MEM_ALLOC_INITIAL_ZERO`: The allocation functions (urUSMDeviceAlloc and others) can decide whether the memory should be pooled or not (for example, depending on size - we could configure this using an environmental variable).

To support 3. I propose introducing `ur_mem_desc_t`, similar to [`ze_device_mem_alloc_flag_t`](https://github.com/oneapi-src/level-zero/blob/4ed13f327d3389285592edcf7598ec3cb2bc712e/include/ze_api.h#LL4253C42-L4253C42). This structure would contain `ur_usm_mem_flags_t` plus a 'pool id'. This ID would be just to isolate the allocations - i.e. only allocations with the same ID can be allocated from the same pool. If it's 0, UR will decide whether to pool or not. I think we can do without an extra function to configure the pool, perhaps just an environment variable.

The final API would look like this:

```c++
enum ur_usm_mem_flags_t {
  UR_MEM_ALLOC_FLAG_BIAS_CACHED,
  UR_MEM_ALLOC_FLAG_BIAS_UNCACHED
  UR_MEM_ALLOC_WRITE_COMBINED,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_HOST,
  UR_MEM_ALLOC_DEVICE_READ_ONLY,
  UR_MEM_USM_ALLOC_BUFFER_LOCATION,
  
  // to match ur_mem_advice_t?
  UR_MEM_ALLOC_NON_ATOMIC_MOSTLY,
  UR_MEM_ALLOC_ATOMIC_MOSTLY,
};

enum ur_mem_advice_t {
  UR_MEM_ADVICE_SET_READ_MOSTLY 
  UR_MEM_ADVICE_CLEAR_READ_MOSTLY
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION 
  UR_MEM_ADVICE_CLEAR_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY 
  UR_MEM_ADVICE_CLEAR_NON_ATOMIC_MOSTLY
  UR_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY
  UR_MEM_ADVICE_BIAS_CACHED 
  UR_MEM_ADVICE_BIAS_UNCACHED 
  UR_MEM_ADVICE_FORCE_UINT32
};

struct ur_mem_desc_t {
  ur_base_desc_t base;
  ur_usm_mem_flags_t flags;
  uint64_t pool_id;
};

// ENV VARIABLE: UR_MEM_POOLING_CONFIG=<Option>
// Similar to: LIBOMPTARGET_LEVEL0_MEMORY_POOL in https://reviews.llvm.org/file/data/jqgt6y5pu672jjffvxsx/PHID-FILE-5olg33bslhgmhdsxeycs/openmp_libomptarget_plugins_level0_src_rtl.cpp
//  <Option>       := 0 | <PoolInfoList>
//  <PoolInfoList> := <PoolInfo>[,<PoolInfoList>]
//  <PoolInfo>     := <MemType>,<PoolId>[,<AllocMax>[,<Capacity>[,<PoolSize>]]]
//  <MemType>      := all | device | host | shared
//  <PoolId>       := Id of specific pool, 0 for all pools
//  <AllocMax>     := positive integer or empty, max allocation size in MB
//                    (default: 1)
//  <Capacity>     := positive integer or empty, number of allocations from
//                    a single block (default: 4)
//  <PoolSize>     := positive integer or empty, max pool size in MB
//                    (default: 256)
```

**Comment by igchor** [comment]
As for memAdvise calls, L0 specifies that "Memory advice may only be supported at a device-specific granularity, such as at a page boundary. In this case, the memory range may be expanded such that the start and end of the range satisfy granularity requirements." I don't think we should automatically expand the range in UR. If a user calls memAdvise on memory that is pooled, expanding the range could affect unrelated allocations that happen to be on the same page. I would propose returning an error if the size and ptr are not aligned to the page but I'm not sure if this is feasible (can we query the exact page size?). Alternatively, we could just do nothing in memAdvise if the memory is pooled (also returning some status perhaps). In that case, it might be useful to allow users to enable/disable pooling (e.g. through a `ur_usm_mem_flags_t` properties).

**Comment by jandres742** [comment]
@igchor :

> We might also consider making ur_usm_mem_flags_t and ur_mem_advice_t

Separation in L0 is because the flags used at allocation are more like a guarantee (applications expect the selected behavior to happen), while the values for advice are just a hint (may or may not happen, depending on underlying support). If we merge them into one, we would need to clarify contract with user.

That's related to your question above:

> . Alternatively, we could just do nothing in memAdvise if the memory is pooled (also returning some status perhaps)

if it is a hint and the adapter cannot support it, then no need for returning error, but if it is a flag, adapter must return an error so application knows capability requested by the flag is not supported.

**Comment by igchor** [comment]
Thanks @jandres742, that makes sense. In that case it might be better to have something like this (remove the duplicated properties and just have both flags and mem advice hints in the ur_mem_desc_t):

```c++
enum ur_usm_mem_flags_t {
  UR_MEM_ALLOC_WRITE_COMBINED,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_HOST,
  UR_MEM_USM_ALLOC_BUFFER_LOCATION,
};

enum ur_mem_advice_t {
  UR_MEM_ADVICE_SET_READ_MOSTLY 
  UR_MEM_ADVICE_CLEAR_READ_MOSTLY
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION 
  UR_MEM_ADVICE_CLEAR_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY 
  UR_MEM_ADVICE_CLEAR_NON_ATOMIC_MOSTLY
  UR_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY
  UR_MEM_ADVICE_BIAS_CACHED 
  UR_MEM_ADVICE_BIAS_UNCACHED 
  UR_MEM_ADVICE_FORCE_UINT32
};

struct ur_mem_desc_t {
  ur_base_desc_t base;
  ur_usm_mem_flags_t flags;
  enum ur_mem_advice_t hint;
  uint64_t pool_id;
};
```

**Comment by jandres742** [comment]
thanks @igchor. So idea here would be usmMemAdvise wouldn't be needed, since already the usmAlloc* did everything, right? cool.

**Comment by igchor** [comment]
@jandres742 it wouldn't be needed for OpenMP case, at least. In general, having usmMemAdvise is probably still useful - I can imagine a use case where the workload characteristic changes over time.

**Comment by igchor** [comment]
Feedback from our discussion today:
- UR_MEM_ALLOC_ZERO_INITIALIZE will not be very useful for OpenMP since they want to avoid any overhead related to sending memset requests to the device. 
- UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE/HOST has similar problems as mem advice. For pooled memory, to guarantee the initial placement, we would need to touch memory from host/device after each allocation. That would introduce extra overhead and could impact unrelated allocations (on the same page).
- having programmatic API (a new function in UR spec) to configure memory pools is preferred over ENV variable

I would suggest removing the UR_MEM_ALLOC_ZERO_INITIALIZE for now since OpenMP would be better off using `pool_id` field and zeroing out the memory on the device by itself.

UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE and UR_MEM_ALLOC_INITIAL_PLACEMENT_HOST could be moved to a separate enum (`enum ur_initial_placement_t`) and treated as hint for pooled memory. We can introduce 'UR_MEM_ALLOC_FORCE_DISABLE_POOLING' to ensure the allocation is not pooled (the allocation would always be page-aligned). This would flag, combined with UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE  or UR_MEM_ALLOC_INITIAL_PLACEMENT_HOST  would guarantee the initial placement.

As for the API for pool configuration: my idea was that by having UR_MEM_POOLING_CONFIG users can configure the pooling behavior without needing to go through OpenMP (LIBOMPTARGET_LEVEL0_MEMORY_POOL might not be necessary anymore - still it would probably be provided for compatibility). However, this makes it harder for OpenMP to modify the pooling defaults. Moreover if there are more applications using UR setting `UR_MEM_POOLING_CONFIG` might affect them as well. Do you think we should actually introduce some programmatic API for pool configuration?

**Comment by jandres742** [comment]
thanks @igchor .

could you elaborate on the pooling config mechanism? not completely sure what we would like to do there, or how different it is from the flags and advise hints you previously posted.

**Comment by igchor** [comment]
@jandres742 the pooling config would be used to configure things like max allocations size (allocation bigger than that would not be pooled), max pool size per context/device, etc.. For env variable It could be similar to what OpenMP exposes:
```c++
// ENV VARIABLE: UR_MEM_POOLING_CONFIG=<Option>
// Similar to: LIBOMPTARGET_LEVEL0_MEMORY_POOL in https://reviews.llvm.org/file/data/jqgt6y5pu672jjffvxsx/PHID-FILE-5olg33bslhgmhdsxeycs/openmp_libomptarget_plugins_level0_src_rtl.cpp
//  <Option>       := 0 | <PoolInfoList>
//  <PoolInfoList> := <PoolInfo>[,<PoolInfoList>]
//  <PoolInfo>     := <MemType>,<PoolId>[,<AllocMax>[,<Capacity>[,<PoolSize>]]]
//  <MemType>      := all | device | host | shared
//  <PoolId>       := Id of specific pool, 0 for all pools
//  <AllocMax>     := positive integer or empty, max allocation size in MB
//                    (default: 1)
//  <Capacity>     := positive integer or empty, number of allocations from
//                    a single block (default: 4)
//  <PoolSize>     := positive integer or empty, max pool size in MB
//                    (default: 256)
```

For programmatic API we would need to allow setting those properties in the code. This list of properties is what we should start with but I imagine it can be extended in future.

**Comment by jandres742** [comment]
thanks @igchor . Yes, I would think it is better to have that in an API, rather than an env var.

**Comment by igchor** [comment]
Ok, in that case perhaps we could go with something like this:

```c++
struct ur_usm_pool_desc_t {
    ur_base_desc_t base;

    size_t max_pool_size;
    size_t max_poolable_size;
    size_t capacity;
    size_t slab_min_size;
};

// creates a pool with given poolId and properties defined by 'desc'
urUSMCreatePool(ur_context_handle_t hContext, uint64_t poolId, struct ur_usm_pool_desc_t *desc);

struct ur_mem_desc_t {
  ur_base_desc_t base;
  ur_usm_mem_flags_t flags;
  ur_mem_advice_t hint;
  uint64_t pool_id;
};

// if 'desc' contains pool ID that was not created using 'urUSMCreatePool' the pool will be created now, using default params
urUSMDeviceAlloc(..., ur_usm_mem_desc_t *desc, ...);
```

OpenMP would be responsible for parsing LIBOMPTARGET_LEVEL0_MEMORY_POOL and calling `urUSMCreatePool` during init.

Also, I did not specify this earlier, but I belive the `pool_id` should be per-context. This is to avoid potential collisions if multiple applications are using UR.

I belive the main concern I and @pbalcer have is whether we feel confident enough to define `ur_usm_pool_desc_t`. We would not like to introduce some API that would be deprecated shortly after, for example by UMA-based API. However, PI already defines those properties (capacity, slab_min_size, etc.) in the description of `SYCL_PI_LEVEL_ZERO_USM_ALLOCATOR` env variable and I think we would need to keep backward compatibility and support them anyway. It should not make much difference whether it's just env variable or programmatic API.

**Comment by vinser52** [comment]
I think we also need to involve OpenMP folks in this discussion. 
@hansangbae could you please take a look?

**Comment by hansangbae** [comment]
The latest suggestion looks OK to me.
Current usage case for zero-initialized memory in OpenMP is too much dependent on pool implementation, so it is better to have OpenMP take care of the feature.
I don't see any problems from the API-based pool configuration and passing memory advice to allocator.

@RaviNarayanaswamy, can you also take a look?

**Comment by RaviNarayanaswamy** [comment]
Can you point me to the document showing how to create poolid

**Comment by igchor** [comment]
> Can you point me to the document showing how to create pool ID.

The idea would be to let user define their own pool IDs (it can be an arbitrary number) `urUSMDeviceAlloc`, `urUSMSharedAlloc` and `urUSMHostAlloc` would accept pool ID through `ur_mem_desc_t`. All allocations with a certain pool ID would be isolated (served from a separate pool) from all other allocations.

Here's and example:
```c++
// arbitrary number from 0 to UINT64_MAX
#define OPENMP_SCRATCH_POOL 1
...

// somewhere during openmp initialization
ur_usm_pool_desc_t  desc;
desc.max_pool_size = ...;
desc.capacity = ...;
urUSMCreatePool(hContext, OPENMP_SCRATCH_POOL , &desc);
...

// on alloc
ur_mem_desc_t mem_desc;
mem_desc.pool_id = OPENMP_SCRATCH_POOL 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
```

With this API a user can choose arbitrary granularity of pooling. For example, If you'd like to have per-device pools you can just use ze_device_handle_t as a pool_id (casted to uint64_t).

**Comment by RaviNarayanaswamy** [comment]
@igchor 
What happends if there are 2 call tourUSMCreatePool with same id
            urUSMCreatePool(hContext, OPENMP_SCRATCH_POOL , &desc);
            urUSMCreatePool(hContext, OPENMP_SCRATCH_POOL , &desc);
Wouldn't  it be better for UMR to provide the pool_id.

**Comment by igchor** [comment]
> @igchor What happens if there are 2 call tourUSMCreatePool with same pool id urUSMCreatePool(hContext, OPENMP_SCRATCH_POOL , &desc); urUSMCreatePool(hContext, OPENMP_SCRATCH_POOL , &desc); Wouldn't it be better for UMR to provide the pool_id.

@RaviNarayanaswamy 

I think that in this case, the second call would return an error. In general it might not be possible to alter the existing pool (.e.g change Slab Size) so it's seems like the best solution.

UR could provide the pool_id but in that case you need to call urUSMCreatePool as many times as you want to to have pools.  If user provides the pool_id then we can create the pool lazily in the urUSM*alloc if needed (using default values).

Additionally, if UR would provide pool_id then the user would need to keep track of them (and in case of per-device pool, would need to map each pool_id into a device).

**Comment by vinser52** [comment]
@igchor if `pool_id` is provided by the user, what is the reason to have the `urUSMCreatePool` function?
I understand the need for this function if `pool_id` is created by UR.

**Comment by vinser52** [comment]
> Current usage case for zero-initialized memory in OpenMP is too much dependent on pool implementation, so it is better to have OpenMP take care of the feature.

After our discussions at oneMemory WG I have the impression that the only requirement for the counter pool is that it is an isolated pool (from other allocations) so that OpenMP RT can return zero-initialized memory to this pool so that for further allocation it gets zero-initilized memory. 

Do we miss something else that prevent you from using dedicated pool provided by UR?

**Comment by igchor** [comment]
> @igchor if `pool_id` is provided by the user, what is the reason to have the `urUSMCreatePool` function? I understand the need for this function if `pool_id` is created by UR.

The only reason is to set `ur_usm_pool_desc_t ` for that particular `pool_id`. For example, if user sets LIBOMPTARGET_LEVEL0_MEMORY_POOL , OpenMP would parse this var and call `urUSMCreatePool` with appropriate params.

**Comment by RaviNarayanaswamy** [comment]
I think the pool_id should be an opaque pointer returned when
void * custom_pool =  urUSMCreatePool(hContext, , &desc);

ur_mem_desc_t mem_desc;
mem_desc.pool_ = custom_pool

**Comment by igchor** [comment]
> I think the pool_id should be an opaque pointer returned when void * custom_pool = urUSMCreatePool(hContext, , &desc);
> 
> ur_mem_desc_t mem_desc; mem_desc.pool_ = custom_pool

@RaviNarayanaswamy sure, we can do that. Are there any other gaps/concerns?

**Comment by RaviNarayanaswamy** [comment]
Thanks @igchor.   This will give us flexibility to create separate pools if we need for custom allocation.

**Comment by hansangbae** [comment]
> @hansangbae
> 
> > Current usage case for zero-initialized memory in OpenMP is too much dependent on pool implementation, so it is better to have OpenMP take care of the feature.
> 
> After our discussions at oneMemory WG I have the impression that the only requirement for the counter pool is that it is an isolated pool (from other allocations) so that OpenMP RT can return zero-initialized memory to this pool so that for further allocation it gets zero-initilized memory.
> 
> Do we miss something else that prevent you from using dedicated pool provided by UR?

I was thinking of supporting zero-initialized pool in OpenMP without considering any pool configuration/isolation mechanism. I don't think it is possible to achieve the current behavior without knowing when the pool implementation allocates memory from L0, so it must be handled in OpenMP as a block of zero-initialized memory created from some UR pool (can be a default pool), and returned to the pool at program exit for example.
The other use case (dedicated scratch pool) is something we can enable with an isolated UR pool configured at pool-creation time.

**Comment by igchor** [comment]
Also, one extra note: as you see I propose to pass `ur_usm_mem_flags_t flags` and
  `ur_mem_advice_t hint` directly to the urUSM*Alloc functions instead of passing to `urUSMCreatePool`. The idea is to let UR decide how to handle each allocation. I considered the following scenarios:
  
1. Mem advice and NULL pool pointer
```c++
ur_mem_desc_t mem_desc;
mem_desc.pool = NULL;
mem_desc.advice = UR_MEM_ADVICE_SET_READ_MOSTLY;
// pool is == NULL, UR can decide to create a dedicated memory pool for 
// READ_MOSTLY and allocate from that or allocate directly from the
// driver/runtime (e.g. L0) 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
  ```

2. Mem advice and non-NULL pool pointer
```c++
ur_mem_desc_t mem_desc;
mem_desc.pool = urCreateUSMPool(hContext, ...);
mem_desc.advice = UR_MEM_ADVICE_SET_READ_MOSTLY;
// same as the previous example, but pool is NOT NULL,
// UR will ignore the advice field if calling memAdvice could
// affect other allocations from the pool.
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
  ```
 3. Flags and NULL pool pointer 
 ```c++
ur_mem_desc_t mem_desc;
mem_desc.pool = NULL;
mem_desc.flags = UR_MEM_ALLOC_FLAG_BIAS_CACHED;
// flag, unlike advice, needs to be respected, since pool pointer is NULL,
// UR can (as in 1.) create a dedicated memory pool or allocate directly from
// driver/runtime (.e.g. L0)
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
  ```
  
4. Flags and non-NULL pool pointer
 ```c++
ur_mem_desc_t mem_desc;
mem_desc.pool = urCreateUSMPool(hContext, ...);
mem_desc.flags = UR_MEM_ALLOC_FLAG_BIAS_CACHED;
// flag, unlike advice, needs to be respected since pool is NOT NULL
// urUSMDeviceAlloc will return an error here 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
  ```
  
The consequence of this API is that there is no way to manually create a pool that would have a certain memory property (for example UR_MEM_ADVICE_READ_MOSTLY or BIAS_CACHED). Instead, in case of mem advice, UR would decide whether to do pooling or not. 

I don't think this is a big problem since I believe we wouldn't create a pool for each possible mem advice in OpenMP anyway. Moreover, our long-term plan is to expose UMA API which would offer this capability. 

@vinser52 @RaviNarayanaswamy Do you think this design is fine or do you see a need to specify mem advice/flags per pool?

**Comment by igchor** [comment]
> > @hansangbae
> > > Current usage case for zero-initialized memory in OpenMP is too much dependent on pool implementation, so it is better to have OpenMP take care of the feature.
> > 
> > 
> > After our discussions at oneMemory WG I have the impression that the only requirement for the counter pool is that it is an isolated pool (from other allocations) so that OpenMP RT can return zero-initialized memory to this pool so that for further allocation it gets zero-initilized memory.
> > Do we miss something else that prevent you from using dedicated pool provided by UR?
> 
> I was thinking of supporting zero-initialized pool in OpenMP without considering any pool configuration/isolation mechanism. I don't think it is possible to achieve the current behavior without knowing when the pool implementation allocates memory from L0, so it must be handled in OpenMP as a block of zero-initialized memory created from some UR pool (can be a default pool), and returned to the pool at program exit for example. The other use case (dedicated scratch pool) is something we can enable with an isolated UR pool configured at pool-creation time.

@hansangbae yes, you are right. We could perhaps tell UR to zero the memory when allocating it from L0 (we could specify this on urCreateUSMPool()). OpenMP would still be responsible for zeroing out the memory on free. However, this approach seems to break the abstraction a bit so I'm not sure if this is the best idea.

**Comment by RaviNarayanaswamy** [comment]
To handle 
Flags and non-NULL pool pointer
ur_mem_desc_t mem_desc;
mem_desc.pool = urCreateUSMPool(hContext, ...);
mem_desc.flags = UR_MEM_ALLOC_FLAG_BIAS_CACHED;
// flag, unlike advice, needs to be respected since pool is NOT NULL
// urUSMDeviceAlloc will return an error here 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);

If .flags was also  added to   ur_usm_pool_desc_t then during CreateUSMPool we can request a particular pool and when urUSMDeviceAlloc is called can check if mem_desc matches the Pool flag.

Regarding ZERO_INITLAIZE_MEMORY.  UMR should allocate memory and initialize the memory,  this would force the memory allocation at memory request.

**Comment by igchor** [comment]
> To handle Flags and non-NULL pool pointer ur_mem_desc_t mem_desc; mem_desc.pool = urCreateUSMPool(hContext, ...); mem_desc.flags = UR_MEM_ALLOC_FLAG_BIAS_CACHED; // flag, unlike advice, needs to be respected since pool is NOT NULL // urUSMDeviceAlloc will return an error here urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
> 
> If .flags was also added to ur_usm_pool_desc_t then during CreateUSMPool we can request a particular pool and when urUSMDeviceAlloc is called can check if mem_desc matches the Pool flag.
> 
> Regarding ZERO_INITLAIZE_MEMORY. UMR should allocate memory and initialize the memory, this would force the memory allocation at memory request.

Yes, we can also have different flags for `urCreateUSMPool` and for `urUSM*Alloc` since some of them make sense only for specific allocations.

It could look like this:

```c++
enum ur_usm_mem_flags_t {
  UR_MEM_ALLOC_WRITE_COMBINED,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE,
  UR_MEM_ALLOC_INITIAL_PLACEMENT_HOST,
  UR_MEM_ALLOC_ZERO_INITIALIZE,
  UR_MEM_USM_ALLOC_BUFFER_LOCATION,
};

enum ur_mem_advice_t {
  UR_MEM_ADVICE_SET_READ_MOSTLY 
  UR_MEM_ADVICE_CLEAR_READ_MOSTLY
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION 
  UR_MEM_ADVICE_CLEAR_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_PREFERRED_LOCATION
  UR_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY 
  UR_MEM_ADVICE_CLEAR_NON_ATOMIC_MOSTLY
  UR_MEM_ADVICE_BIAS_CACHED 
  UR_MEM_ADVICE_BIAS_UNCACHED 
};

struct ur_mem_desc_t {
  ur_base_desc_t base;
  
  ur_usm_mem_flags_t flags;
  ur_mem_advice_t hint;
  
  void* pool_id;
};

enum ur_usm_pool_mem_flags_t {
    UR_MEM_ALLOC_WRITE_COMBINED,
    UR_MEM_ALLOC_ZERO_INITIALIZE,
    UR_MEM_ALLOC_BIAS_CACHED,
    UR_MEM_ALLOC_BIAS_UNCACHED 
};

struct ur_usm_pool_desc_t {
    ur_base_desc_t base;

    ur_usm_pool_mem_flags_t flags;

    size_t max_pool_size;
    size_t max_poolable_size;
    size_t capacity;
    size_t slab_min_size;
};

// 1. For non-NULL pool
ur_mem_desc_t mem_desc;
mem_desc.pool = urCreateUSMPool(hContext, ...);
mem_desc.flags = 0; // if pool is non-NULL, flags should be 0
// hints are fine since they can be ignored, or UR can create sub-pool
mem_desc.hints = UR_MEM_ADVICE_SET_READ_MOSTLY; 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);

// 2. For NULL pool
ur_mem_desc_t mem_desc;
mem_desc.pool = NULL;
// if pool is NULL, flags can be safely specified, UR will either create dedicated
// pool or will allocate directly from driver/runtime
mem_desc.flags = UR_MEM_ALLOC_WRITE_COMBINED ; 
// same is true for hints
mem_desc.hints = UR_MEM_ADVICE_SET_READ_MOSTLY; 
urUSMDeviceAlloc(hContext, hDevice, &mem_desc, size, align, &ptr);
```

**Comment by vinser52** [comment]
> However, we could perhaps tell UR to zero the memory when allocating it from L0

I thought that memory allocated by `zeMemAllocDevice` | `zeMemAllocShared` | `zeMemAllocHost` is always zero-initialized like `mmap` with `MAP_ANONYMOUS`. 

@jandres742 Can you comment if my assumption is correct?

**Comment by hansangbae** [comment]
> > However, we could perhaps tell UR to zero the memory when allocating it from L0
> 
> I thought that memory allocated by `zeMemAllocDevice` | `zeMemAllocShared` | `zeMemAllocHost` is always zero-initialized like `mmap` with `MAP_ANONYMOUS`.
> 
> @jandres742 Can you comment if my assumption is correct?

Is this documented somewhere?

**Comment by jandres742** [comment]
@vinser52 @hansangbae 

That is not specified. Memory allocated through `zeMemAlloc` APIs is not initialized to any value. Users need to use `zeCommandListAppendMemoryFill` for instance to initialize it to zero, which is basically what the L0 adapter would do if we introduce the ZERO_INITIALIZED flag in the UR.
