### ISSUE TITLE
Stop using _<name>  reserved identifiers

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#18]
Unified Runtime appears to have followed the example of OpenCL and used `_<name>` in typedefs of the opaque API objects e.g. [`_ur_module_handle_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L111).

This is actually illegal in both the C and C++ specifications as all identifiers with the _  prefix are reserved for standard library implementation and internals.

We should rename the structs in this pattern.

**Comment by kbenzie** [comment]
I've also seen this cause errors in the Sphinx build. The reStructuredText is referring to `<name>` for an `enum` or similar but not being able to resolve it name because Doxygen has parsed the `enum` type name it as `_<name>`, `<name>` actually refers to a `typedef`.

**Comment by pbalcer** [comment]
I was looking over #23 and also noticed that many identifiers use `_t` suffix which is reserved by POSIX (often for both `struct` definition and in the typedef). Not sure if this is worth though changing since conflicts are very unlikely.

glibc docs have a handy list of reserved names: https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by FranklandJack** [comment]
I think the `_t` is a good point, but like you say conflicts are very unlikely. Adapters could in theory include POSIX headers, but I think the probability of them defining something like `ur_context_handle_t` is so low that we can probably ignore this issue for the time being. Worth bearing in mind though in case it does come up at some point.
