### ISSUE TITLE
Create a minimal header only containing basic UR types

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#1890]
The `ur_api.h` header is 12K lines and this may result in longer compile times than desirable as noted [here](https://github.com/intel/llvm/pull/14145#discussion_r1684665066).

We should split out the UR basic types, handle definitions, and any other necessary non struct/function types which would let us avoid including the `ur_api.h` header when it's not necessary. This would then also be included by `ur_api.h` and existing uses would see no change.

**Comment by RossBrunton** [comment]
I've been looking into this and have managed to hack together a split where one file contains functions, and one contains things which are not functions. However, I'm not seeing any noticeable performance differences. The e2e test run itself seems to only differ in speed by a few seconds (for a 500 second run) on my system, which feels like random noise.

I also looked into profiling the compiler, and as far as I can tell, the full header takes 10ms to parse, while the reduced header takes 7ms. Which suggests that the difference in performance isn't going to be meaningful when compiles take several seconds. It's also a C header, rather than a heavily templated C++ header, so there's probably not going to be lots of complicated templatey stuff.

@AlexeySachkov , are there any particular situations or codebases you are worried about that I could look into?

**Comment by RossBrunton** [comment]
So I had a look at building the SYCL CTS with the split header vs the full header. The compile takes about 3 and a half hours, and the time difference between the two header types is about a minute, which I think is just random noise.

**Comment by AlexeySachkov** [comment]
@RossBrunton, thanks for doing those experiments.

My comment was not baked by any data points, I was just in general concerned about bringing more code into `sycl.hpp` especially considering that we did have issue with `ur_print.hpp`.

The  data you have suggests that remaining headers are not significant with respect to compile times and if so, I'm fine with closing this issue as won't fix.
