### ISSUE TITLE
Add CI testing for builds with multiple adapters

### ISSUE THREAD

**Issue by RossBrunton** [oneapi-src/unified-runtime#2081]
Currently, we run a single build per adapter (e.g. one build for OpenCL, one build for Level Zero, etc.), which can miss failures in the multi-adapter dispatcher, ur_ldrddi.cpp (e.g. https://github.com/oneapi-src/unified-runtime/pull/2048 ).

We should add a CI workflow for the Build & Test HW and e2e jobs that use a build that has multiple adapters enabled (although it can use only one adapter for the test).

**Comment by martygrant** [comment]
> (although it can use only one adapter for the test).

Could it be an entirely new job that does two test runs, one for each adapter?

**Comment by RossBrunton** [comment]
@martygrant I could do that, but I'm concerned about how long the job will take to run. Once I have something working I'll have a look at how long it takes.

**Comment by pbalcer** [comment]
Just keep in mind that not all systems have CUDA and HIP installed, and keeping the versions of those things up-to-date might be annoying.

I think one simple solution here would be to use `ONEAPI_DEVICE_SELECTOR` in the tests instead of `UR_ADAPTERS_FORCE_LOAD`: https://github.com/oneapi-src/unified-runtime/blob/main/source/loader/ur_libapi.cpp

The builds always have at least two adapters since the mock adapter is built unconditionally.
