### ISSUE TITLE
[HIP] getGlobalVariablePointer error

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/unified-runtime#2475]
Running the program shows the following error. Thanks for your comments.

https://github.com/zjin-lcf/HeCBench/tree/master/src/adamw-sycl

clang version 20.0.0git (https://github.com/intel/llvm.git 746a2bd12821edd8b9982f9d16daf7962bd68a4b)

<HIP>[ERROR]:
UR HIP ERROR:
        Value:           500
        Name:            hipErrorNotFound
        Description:     named symbol not found
        Function:        getGlobalVariablePointer
        Source Location: /storage/_deps/unified-runtime-src/source/adapters/hip/program.cpp:253

<HIP>[ERROR]:
UR HIP ERROR:
        Value:           UR_RESULT_ERROR_UNKNOWN
        Function:        deviceGlobalCopyHelper
        Source Location: /storage/_deps/unified-runtime-src/source/adapters/hip/enqueue.cpp:1724

**Comment by ldrumm** [comment]
Thanks for the report.

I've recreated this locally, and have tracked this down to a similar problem we saw in the CUDA adapter.

Due to some deficiencies in implementation, `device_global` objects won't presently work unless they're of external visibility i.e. not `static`. We fixed this in the CUDA adapter, buit it requires a slightly different approach in HIP, which I should be able to look into after the hols.

For the moment, the following patch should get adamw-sycl working:

```diff
diff --git a/src/adamw-sycl/kernels.h b/src/adamw-sycl/kernels.h
index 7eaaa7a9..03aba9c6 100644
--- a/src/adamw-sycl/kernels.h
+++ b/src/adamw-sycl/kernels.h
@@ -2,7 +2,6 @@
 static const uint8_t _bitmask(15);
 static const uint8_t _right_pack_bitmask(_bitmask << 4);
 
-static
 sycl::ext::oneapi::experimental::device_global<const float[16]> _exp_qmap {
                                                          -0.8875,
                                                          -0.6625,
@@ -22,7 +21,6 @@ sycl::ext::oneapi::experimental::device_global<const float[16]> _exp_qmap {
                                                          1.0000
                                                      };
 
-static
 sycl::ext::oneapi::experimental::device_global<const float[15]> _exp_qmidpt {
 
                                                            -0.775,
@@ -42,7 +40,6 @@ sycl::ext::oneapi::experimental::device_global<const float[15]> _exp_qmidpt {
                                                            0.94375,
                                                        };
 
-static
 sycl::ext::oneapi::experimental::device_global<const float[16]> _sq_qmap {
                                                         0.0625,
                                                         0.1250,
@@ -62,7 +59,6 @@ sycl::ext::oneapi::experimental::device_global<const float[16]> _sq_qmap {
                                                         1.0000,
                                                     };
 
-static
 sycl::ext::oneapi::experimental::device_global<const float[15]> _sq_qmidpt {
                                                           0.09375,
                                                           0.15625,
```

This is a related ticket:
- https://github.com/intel/llvm/issues/15329
Here are 2 patches from Hugh Delaney fixing the equivalent CUDA problem:
- https://github.com/intel/llvm/pull/15224
- https://github.com/intel/llvm/pull/15148

**Comment by jinz2014** [comment]
I didn't know that the issue was already reported. I will close the issue. You have a good holiday.
