### ISSUE TITLE
`urDeviceSelectBinary` should take an array of binary sizes

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#252]
The `urDeviceSelectBinary` entry point currently has the following signature: 

```cpp
urDeviceSelectBinary(
    ur_device_handle_t hDevice,                     ///< [in] handle of the device to select binary for.
    const uint8_t** ppBinaries,                     ///< [in] the array of binaries to select from.
    uint32_t NumBinaries,                           ///< [in] the number of binaries passed in ppBinaries. Must greater than or
                                                    ///< equal to zero.
    uint32_t* pSelectedBinary                       ///< [out] the index of the selected binary in the input array of binaries.
                                                    ///< If a suitable binary was not found the function returns ${X}_INVALID_BINARY.
    );
```

We should pass an additional argument, which will be an array of sizes for the length of each binary.

**Comment by kbenzie** [comment]
The `ppBinaries` argument has a different type as well, `uint8_t**` rather than [pi_decice_binary*](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L1073). There's actually quite a lot of data members in [pi_device_binary_struct](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L817-L868) which `pi_device_binary` is an poitner alias of.

I don't know if we need to expose all that but it seems likely that info is there for a reason and we are currently not in a position to do what PI does.
