### ISSUE TITLE
Perform Fuzz Testing

### ISSUE THREAD

**Issue by wlemkows** [oneapi-src/unified-runtime#566]
Fuzz testing is a common type of automated testing where randomized inputs are injected into the interfaces of a system.
It includes testing the system with invalid, negative, malformed or unexpected inputs.

Any interface can be a target for fuzzing. Fuzzing can quickly identify areas where unsanitized input is improperly handled and hence is extremely effective in finding critical security issues without needing to fully understand the mechanics of the underlying software.
It is worth using a fuzzing tool to implement such tests, for example LibFuzzer for C/C++.

**Comment by pbalcer** [comment]
Partially done in #795. Since UR is a stateful API with *many* entry points, fuzz testing is a bit awkward. We followed libfuzzer [docs](https://github.com/google/fuzzing/blob/master/docs/structure-aware-fuzzing.md#fuzzing-stateful-apis) recommendations for stateful APIs, and @PatKamin implemented a fuzzing solution similar to that of [gRPC](https://github.com/google/fuzzing/blob/master/docs/structure-aware-fuzzing.md#example-grpc-api-fuzzer).
The fuzz tests will run with known-working fuzz corpus for every change, and there is a nightly job for the fuzzer to run for longer. This is to prevent PR checks from being flaky due to the non-deterministic nature of fuzzing.

The current implementation covers the core APIs, but some gaps still need to be addressed. Not all arguments in the existing functions are also subject to fuzzing for now.

I'm closing this issue, and we will create new ones as needed for additional fuzzer funcionality.
